version: '3.8'

services:
 dev:
  build:
   context: .
   dockerfile: Dockerfile
  command: sleep infinity
  volumes:
   - ../:/app
  networks:
   - dashboard_network
  depends_on:
   - database
  restart: unless-stopped

 database:
  image: mysql
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:
   - mysql:/var/lib/mysql
   - mysql_config:/etc/mysql
  networks:
   - dashboard_network

 grafana:
  image: grafana/grafana-oss:8.2.0
  ports:
   - 3000:3000
  networks:
   - dashboard_network

 adminer:
  image: adminer
  ports:
   - 8080:8080
  
  networks:
   - dashboard_network

volumes:
 mysql:
 mysql_config:

networks:
  dashboard_network:
   name: dashboard_network
